name: amdjs
description: JavaScript AMD (Asynchronous Module Definition) Dart interoperability.
version: 2.0.3
homepage: https://github.com/gmpassos/amdjs.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dom_tools: ^2.1.0
  swiss_knife: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  dependency_validator: ^3.1.0

#dependency_overrides:
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife


