name: amdjs
description: JavaScript AMD (Asynchronous Module Definition) Dart interoperability.
version: 2.0.0-nullsafety.1
homepage: https://github.com/gmpassos/amdjs.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dom_tools: ^2.0.0-nullsafety.1
  swiss_knife: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5

#dependency_overrides:
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife


