name: amdjs
description: JavaScript AMD (Asynchronous Module Definition) Dart interoperability.
version: 1.0.7
homepage: https://github.com/gmpassos/amdjs.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dom_tools: ^1.3.14
    #path: ../dom_tools
  swiss_knife: ^2.5.16
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
