name: amdjs
description: JavaScript AMD (Asynchronous Module Definition) Dart interoperability.
version: 2.0.4
homepage: https://github.com/gmpassos/amdjs.dart

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dom_tools: ^2.3.2
  swiss_knife: ^3.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.14
  dependency_validator: ^4.1.2

#dependency_overrides:
#  dom_tools:
#    path: ../dom_tools
#  swiss_knife:
#    path: ../swiss_knife


