name: amdjs
description: JavaScript AMD (Asynchronous Module Definition) Dart interoperability.
version: 1.0.6
homepage: https://github.com/gmpassos/amdjs.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dom_tools: ^1.3.7
    #path: ../dom_tools
  swiss_knife: ^2.5.8
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
